In [92]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('New_Processed.csv')

In [3]:
df = df.drop(['Unnamed: 0'], axis=1).reset_index()
df.drop('index', axis =1, inplace= True)

In [4]:
df

,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,Resistance.4,...,Field.12,Resistance.12,Field.13,Resistance.13,Field.14,Resistance.14,Field.15,Resistance.15,Field.16,Resistance.16
0,-30000.136230,-22.015110,-30000.237793,-25.658748,-30000.161621,-25.660312,-30000.314453,-33.061638,-30000.210449,-44.530813,...,-30000.313965,-80.260118,-30000.322754,-83.890323,-30000.221191,-85.732440,-30000.284668,-83.998552,-30000.316895,-90.271623
1,-29000.178223,-22.151393,-29000.287109,-25.683152,-29000.372070,-25.689180,-29000.372070,-33.144423,-29000.366211,-45.432488,...,-29000.218750,-81.371335,-28000.401855,-85.515418,-28000.204590,-86.170185,-29000.333496,-84.980987,-28000.130859,-91.795915
2,-28000.385742,-22.080572,-28000.371582,-25.715422,-28000.139648,-25.687288,-28000.182617,-33.225642,-28000.169922,-46.053477,...,-28000.128906,-82.243520,-26000.413086,-86.766550,-26000.185547,-86.708710,-28000.147949,-85.756800,-26000.150391,-93.072230
3,-27000.240723,-22.112155,-27000.218262,-25.730780,-27000.424316,-25.694467,-27000.155762,-33.243597,-27000.155762,-46.523953,...,-27000.273438,-82.889482,-24000.156250,-87.909435,-24000.391113,-87.172280,-27000.268066,-86.398370,-24000.210938,-93.792655
4,-26000.390625,-22.147685,-26000.377441,-25.701777,-26000.303711,-25.710887,-26000.166992,-33.336875,-26000.153320,-46.770880,...,-26000.177734,-83.388545,-22000.428223,-89.031960,-22000.169922,-87.781498,-26000.180176,-86.841875,-22000.412109,-94.835125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,-26000.207520,-22.196493,-26000.401855,-25.739880,-26000.191406,-25.675908,-26000.421387,-33.760388,-26000.409668,-47.806663,...,-26000.394043,-82.454370,NaN,NaN,NaN,NaN,-26000.306152,-86.519620,NaN,NaN
138,-27000.218262,-22.161595,-27000.259766,-25.714250,-27000.149902,-25.666777,-27000.237793,-33.742722,-27000.281738,-47.779592,...,-27000.090332,-82.253355,NaN,NaN,NaN,NaN,-27000.145020,-86.110823,NaN,NaN
139,-28000.224121,-22.121645,-28000.259766,-25.705235,-28000.175781,-25.660190,-28000.131348,-33.705265,-28000.147949,-47.750485,...,-28000.379883,-81.932025,NaN,NaN,NaN,NaN,-28000.158691,-85.821085,NaN,NaN
140,-29000.140625,-22.134743,-29000.355469,-25.668198,-29000.259766,-25.639682,-29000.240723,-33.707752,-29000.240234,-47.726520,...,-29000.159668,-81.612302,NaN,NaN,NaN,NaN,-29000.227051,-85.538120,NaN,NaN
141,-30000.262695,-22.085910,-30000.316895,-25.672373,-30000.207520,-25.654003,-30000.205078,-33.690795,-30000.331543,-47.688212,...,-30000.294922,-81.445288,NaN,NaN,NaN,NaN,-30000.333496,-85.211238,NaN,NaN

In [20]:
#df = df.dropna()

In [212]:
asymm = pd.DataFrame()

In [214]:
n=0
r = df[df.columns[1::2]]
f = df[df.columns[0::2]]
for column in r:
   
    #Row Count
    total_rows = r.iloc[:,n:n+1].count().astype(int)
    total_rows = int(total_rows)
    halfrows= int(total_rows/2)

    #for columns in r:
    rx1 = r.iloc[:halfrows,n:n+1]
    rx2 = r.iloc[halfrows:total_rows,n:n+1].reset_index()
    rx2.drop('index', axis =1, inplace= True)

    #Antisymmetrization
    up = rx1.subtract(rx2, fill_value=0)
    down = rx2.subtract(rx1, fill_value=0)
    
    resistance = pd.concat([up, down], axis=0, ignore_index=True)
    field = f.iloc[:,n:n+1]
    
    processed = pd.concat([field, resistance], axis=1)
    asymm = pd.concat([asymm, processed], axis=1)
    n=n+1

In [114]:
n=1
df[df.columns[1::2]] #starting from 1 to end every n column

,Resistance,Resistance.1,Resistance.2,Resistance.3,Resistance.4,Resistance.5,Resistance.6,Resistance.7,Resistance.8,Resistance.9,Resistance.10,Resistance.11,Resistance.12,Resistance.13,Resistance.14,Resistance.15,Resistance.16
0,-22.015110,-25.658748,-25.660312,-33.061638,-44.530813,-60.785188,-65.132320,-67.267882,-68.493575,-72.193673,-76.124375,-80.584245,-80.260118,-83.890323,-85.732440,-83.998552,-90.271623
1,-22.151393,-25.683152,-25.689180,-33.144423,-45.432488,-61.693975,-65.241010,-68.081292,-68.794705,-72.930390,-76.914563,-81.127960,-81.371335,-85.515418,-86.170185,-84.980987,-91.795915
2,-22.080572,-25.715422,-25.687288,-33.225642,-46.053477,-62.549870,-65.341790,-68.761290,-69.078203,-73.666233,-77.523153,-81.716178,-82.243520,-86.766550,-86.708710,-85.756800,-93.072230
3,-22.112155,-25.730780,-25.694467,-33.243597,-46.523953,-63.269487,-65.443547,-69.194110,-69.411182,-74.167800,-77.962742,-82.432540,-82.889482,-87.909435,-87.172280,-86.398370,-93.792655
4,-22.147685,-25.701777,-25.710887,-33.336875,-46.770880,-63.826057,-65.519567,-69.650982,-69.682195,-74.593392,-78.480845,-83.250070,-83.388545,-89.031960,-87.781498,-86.841875,-94.835125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,-22.196493,-25.739880,-25.675908,-33.760388,-47.806663,-65.542430,-65.454235,-70.603045,NaN,-74.511668,-78.295322,NaN,-82.454370,NaN,NaN,-86.519620,NaN
138,-22.161595,-25.714250,-25.666777,-33.742722,-47.779592,-65.450412,-65.368355,-70.442980,NaN,-74.276455,-78.089938,NaN,-82.253355,NaN,NaN,-86.110823,NaN
139,-22.121645,-25.705235,-25.660190,-33.705265,-47.750485,-65.335403,-65.289280,-70.342205,NaN,-74.170020,-77.803088,NaN,-81.932025,NaN,NaN,-85.821085,NaN
140,-22.134743,-25.668198,-25.639682,-33.707752,-47.726520,-65.213422,-65.177823,-70.174123,NaN,-74.044095,-77.673792,NaN,-81.612302,NaN,NaN,-85.538120,NaN
141,-22.085910,-25.672373,-25.654003,-33.690795,-47.688212,-65.092700,-65.077422,-70.065075,NaN,-73.878122,-77.439005,NaN,-81.445288,NaN,NaN,-85.211238,NaN

In [84]:
n=0
temp_df = df.iloc[:,n:n+2]
#n = Field, n+1 = resistance

In [62]:
tr = len(temp_df)
hr = int(tr/2)

In [63]:
rx1 = temp_df.iloc[:hr,1:]
rx2 = temp_df.iloc[hr:,1:].reset_index()
rx2.drop('index', axis =1, inplace= True)

In [66]:
up = rx1.subtract(rx2, fill_value=0)
down = rx2.subtract(rx1, fill_value=0)
    
resistance = pd.concat([up, down], axis=0, ignore_index=True)

In [69]:
field = temp_df.iloc[:,:1]
processed = pd.concat([field, resistance], axis=1)

In [129]:
r = df[df.columns[1::2]]
r

,Resistance,Resistance.1,Resistance.2,Resistance.3,Resistance.4,Resistance.5,Resistance.6,Resistance.7,Resistance.8,Resistance.9,Resistance.10,Resistance.11,Resistance.12,Resistance.13,Resistance.14,Resistance.15,Resistance.16
0,-22.015110,-25.658748,-25.660312,-33.061638,-44.530813,-60.785188,-65.132320,-67.267882,-68.493575,-72.193673,-76.124375,-80.584245,-80.260118,-83.890323,-85.732440,-83.998552,-90.271623
1,-22.151393,-25.683152,-25.689180,-33.144423,-45.432488,-61.693975,-65.241010,-68.081292,-68.794705,-72.930390,-76.914563,-81.127960,-81.371335,-85.515418,-86.170185,-84.980987,-91.795915
2,-22.080572,-25.715422,-25.687288,-33.225642,-46.053477,-62.549870,-65.341790,-68.761290,-69.078203,-73.666233,-77.523153,-81.716178,-82.243520,-86.766550,-86.708710,-85.756800,-93.072230
3,-22.112155,-25.730780,-25.694467,-33.243597,-46.523953,-63.269487,-65.443547,-69.194110,-69.411182,-74.167800,-77.962742,-82.432540,-82.889482,-87.909435,-87.172280,-86.398370,-93.792655
4,-22.147685,-25.701777,-25.710887,-33.336875,-46.770880,-63.826057,-65.519567,-69.650982,-69.682195,-74.593392,-78.480845,-83.250070,-83.388545,-89.031960,-87.781498,-86.841875,-94.835125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,-22.196493,-25.739880,-25.675908,-33.760388,-47.806663,-65.542430,-65.454235,-70.603045,NaN,-74.511668,-78.295322,NaN,-82.454370,NaN,NaN,-86.519620,NaN
138,-22.161595,-25.714250,-25.666777,-33.742722,-47.779592,-65.450412,-65.368355,-70.442980,NaN,-74.276455,-78.089938,NaN,-82.253355,NaN,NaN,-86.110823,NaN
139,-22.121645,-25.705235,-25.660190,-33.705265,-47.750485,-65.335403,-65.289280,-70.342205,NaN,-74.170020,-77.803088,NaN,-81.932025,NaN,NaN,-85.821085,NaN
140,-22.134743,-25.668198,-25.639682,-33.707752,-47.726520,-65.213422,-65.177823,-70.174123,NaN,-74.044095,-77.673792,NaN,-81.612302,NaN,NaN,-85.538120,NaN
141,-22.085910,-25.672373,-25.654003,-33.690795,-47.688212,-65.092700,-65.077422,-70.065075,NaN,-73.878122,-77.439005,NaN,-81.445288,NaN,NaN,-85.211238,NaN

In [139]:
f = df[df.columns[0::2]]
f

,Field,Field.1,Field.2,Field.3,Field.4,Field.5,Field.6,Field.7,Field.8,Field.9,Field.10,Field.11,Field.12,Field.13,Field.14,Field.15,Field.16
0,-30000.136230,-30000.237793,-30000.161621,-30000.314453,-30000.210449,-30000.358398,-30000.219238,-30000.303223,-30000.305664,-30000.161133,-30000.317383,-30000.297852,-30000.313965,-30000.322754,-30000.221191,-30000.284668,-30000.316895
1,-29000.178223,-29000.287109,-29000.372070,-29000.372070,-29000.366211,-29000.270996,-29000.429199,-29000.202637,-28000.279297,-29000.374512,-29000.227051,-28000.150391,-29000.218750,-28000.401855,-28000.204590,-29000.333496,-28000.130859
2,-28000.385742,-28000.371582,-28000.139648,-28000.182617,-28000.169922,-28000.325195,-28000.185547,-28000.128418,-26000.188477,-28000.187988,-28000.156738,-26000.104004,-28000.128906,-26000.413086,-26000.185547,-28000.147949,-26000.150391
3,-27000.240723,-27000.218262,-27000.424316,-27000.155762,-27000.155762,-27000.229492,-27000.189453,-27000.287109,-24000.232422,-27000.322754,-27000.169434,-24000.169922,-27000.273438,-24000.156250,-24000.391113,-27000.268066,-24000.210938
4,-26000.390625,-26000.377441,-26000.303711,-26000.166992,-26000.153320,-26000.369141,-26000.344238,-26000.311523,-22000.131348,-26000.196777,-26000.174805,-22000.384277,-26000.177734,-22000.428223,-22000.169922,-26000.180176,-22000.412109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,-26000.207520,-26000.401855,-26000.191406,-26000.421387,-26000.409668,-26000.142578,-26000.210449,-26000.224121,NaN,-26000.385254,-26000.385742,NaN,-26000.394043,NaN,NaN,-26000.306152,NaN
138,-27000.218262,-27000.259766,-27000.149902,-27000.237793,-27000.281738,-27000.136719,-27000.248535,-27000.089844,NaN,-27000.251465,-27000.068359,NaN,-27000.090332,NaN,NaN,-27000.145020,NaN
139,-28000.224121,-28000.259766,-28000.175781,-28000.131348,-28000.147949,-28000.153320,-28000.112305,-28000.098145,NaN,-28000.382324,-28000.235352,NaN,-28000.379883,NaN,NaN,-28000.158691,NaN
140,-29000.140625,-29000.355469,-29000.259766,-29000.240723,-29000.240234,-29000.254395,-29000.149414,-29000.174805,NaN,-29000.188477,-29000.183105,NaN,-29000.159668,NaN,NaN,-29000.227051,NaN
141,-30000.262695,-30000.316895,-30000.207520,-30000.205078,-30000.331543,-30000.213379,-30000.265625,-30000.149902,NaN,-30000.279297,-30000.273438,NaN,-30000.294922,NaN,NaN,-30000.333496,NaN

In [203]:
n=14
total_rows = r.iloc[:,n:n+1].count()
total_rows.astype(int)
total_rows

Resistance.14    106
dtype: int64

In [211]:
n = 16
#Row Count
#total_rows = len(r.iloc[:,n:n+1])
total_rows = r.iloc[:,n:n+1].count().astype(int)
total_rows = int(total_rows)
halfrows= int(total_rows/2)
halfrows

53

In [178]:
n=4
#for columns in r:
rx1 = r.iloc[:halfrows,n:n+1]
rx2 = r.iloc[halfrows:total_rows,n:n+1].reset_index()
rx2.drop('index', axis =1, inplace= True)

#Antisymmetrization
up = rx1.subtract(rx2, fill_value=0)
down = rx2.subtract(rx1, fill_value=0)

In [179]:
resistance = pd.concat([up, down], axis=0, ignore_index=True)
#resistance.drop('index', axis =1, inplace= True)
resistance

     Resistance.4
0        4.583510
1        3.705395
2        3.104127
3        2.661073
4        2.460803
..            ...
137      1.395000
138      1.387430
139      1.405390
140      1.412355
141      1.438077

[142 rows x 1 columns]

In [180]:
field = f.iloc[:,n:n+1]
processed = pd.concat([field, resistance], axis=1)
#asymm = asymm.append(processed, ignore_index= True)
asymm = pd.concat([asymm, processed], axis=1)
n=n+1

          Field.3  Resistance.3       Field.4  Resistance.4
0   -30000.314453      1.615470 -30000.210449      4.583510
1   -29000.372070      1.529547 -29000.366211      3.705395
2   -28000.182617      1.438363 -28000.169922      3.104127
3   -27000.155762      1.432178 -27000.155762      2.661073
4   -26000.166992      1.324077 -26000.153320      2.460803
..            ...           ...           ...           ...
137 -26000.421387      0.926648 -26000.409668      1.395000
138 -27000.237793      0.939628 -27000.281738      1.387430
139 -28000.131348      0.959350 -28000.147949      1.405390
140 -29000.240723      0.969570 -29000.240234      1.412355
141 -30000.205078      0.993260 -30000.331543      1.438077

[142 rows x 4 columns]

In [215]:
asymm

,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,Resistance.4,...,Field.12,Resistance.12,Field.13,Resistance.13,Field.14,Resistance.14,Field.15,Resistance.15,Field.16,Resistance.16
0,-30000.136230,1.222740,-30000.237793,1.149965,-30000.161621,1.147850,-30000.314453,1.615470,-30000.210449,4.583510,...,-30000.313965,3.168075,-30000.322754,5.180870,-30000.221191,1.145553,-30000.284668,3.222593,-30000.316895,2.545185
1,-29000.178223,1.128612,-29000.287109,1.119700,-29000.372070,1.107695,-29000.372070,1.529547,-29000.366211,3.705395,...,-29000.218750,2.237953,-28000.401855,4.009182,-28000.204590,1.230253,-29000.333496,2.574825,-28000.130859,1.682973
2,-28000.385742,1.162935,-28000.371582,1.036650,-28000.139648,1.066295,-28000.182617,1.438363,-28000.169922,3.104127,...,-28000.128906,1.574232,-26000.413086,3.308720,-26000.185547,1.228662,-28000.147949,2.114240,-26000.150391,0.959007
3,-27000.240723,1.117142,-27000.218262,1.013153,-27000.424316,1.063810,-27000.155762,1.432178,-27000.155762,2.661073,...,-27000.273438,1.169310,-24000.156250,2.813965,-24000.391113,1.343665,-27000.268066,1.723758,-24000.210938,0.759383
4,-26000.390625,1.117272,-26000.377441,1.014878,-26000.303711,1.022958,-26000.166992,1.324077,-26000.153320,2.460803,...,-26000.177734,0.983725,-22000.428223,2.271883,-22000.169922,1.310525,-26000.180176,1.474995,-22000.412109,0.243860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,-26000.207520,1.017362,-26000.401855,1.000802,-26000.191406,1.081637,-26000.421387,0.926648,-26000.409668,1.395000,...,-26000.394043,2.013443,NaN,NaN,NaN,NaN,-26000.306152,1.964535,NaN,NaN
138,-27000.218262,1.053523,-27000.259766,1.052757,-27000.149902,1.093663,-27000.237793,0.939628,-27000.281738,1.387430,...,-27000.090332,2.027168,NaN,NaN,NaN,NaN,-27000.145020,1.987652,NaN,NaN
139,-28000.224121,1.093467,-28000.259766,1.071365,-28000.175781,1.113728,-28000.131348,0.959350,-28000.147949,1.405390,...,-28000.379883,2.120453,NaN,NaN,NaN,NaN,-28000.158691,1.989565,NaN,NaN
140,-29000.140625,1.121752,-29000.355469,1.111702,-29000.259766,1.141507,-29000.240723,0.969570,-29000.240234,1.412355,...,-29000.159668,2.089123,NaN,NaN,NaN,NaN,-29000.227051,1.991915,NaN,NaN
141,-30000.262695,1.191690,-30000.316895,1.124687,-30000.207520,1.157980,-30000.205078,0.993260,-30000.331543,1.438077,...,-30000.294922,2.028392,NaN,NaN,NaN,NaN,-30000.333496,2.024750,NaN,NaN