In [6]:
import pandas as pd
import numpy as np
#from pandas.compat import StringIO

In [42]:
df = pd.read_csv('0.1mA_10K_RvH.dat', 
                 sep=",", 
                 skiprows=17, 
                 usecols=[2,3,26], 
                 names=['Temperature (K)','Field (Oe)','Resistance Ch2 (Ohms)'])

In [43]:
df

     Temperature (K)    Field (Oe)  Resistance Ch2 (Ohms)
0          10.000251 -30000.248047              -88.32483
1           9.999456 -30000.259766              -88.32461
2          10.000415 -30000.281250              -88.32465
3          10.000072 -30000.271484              -88.32282
4           9.999707 -28000.402344              -88.32848
..               ...           ...                    ...
243         9.999805 -28000.380859              -88.40498
244        10.000442 -30000.292969              -88.39152
245         9.999734 -30000.335938              -88.39152
246        10.000090 -30000.314453              -88.39072
247         9.999842 -30000.314453              -88.39090

[248 rows x 3 columns]

In [58]:
file_name = 'RvH_{}.dat'

In [59]:
df1 = pd.concat([pd.read_csv(file_name.format(i), error_bad_lines=False, sep=",", 
                 skiprows=17, 
                 usecols=[2,3,26], 
                 names=['Temperature (K)','Field (Oe)','Resistance Ch2 (Ohms)']) for i in range(1, 3)])

In [60]:
df1

     Temperature (K)    Field (Oe)  Resistance Ch2 (Ohms)
0          10.000251 -30000.248047              -88.32483
1           9.999456 -30000.259766              -88.32461
2          10.000415 -30000.281250              -88.32465
3          10.000072 -30000.271484              -88.32282
4           9.999707 -28000.402344              -88.32848
..               ...           ...                    ...
243         9.999858 -28000.158203              -88.49976
244        10.000726 -30000.402344              -88.47413
245        10.000354 -30000.380859              -88.47458
246         9.999898 -30000.402344              -88.47482
247         9.999430 -30000.445312              -88.46860

[496 rows x 3 columns]