In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

In [3]:
df = pd.read_csv('S143B_Raw.csv')

In [4]:
df.head()

          Field  Resistance
0 -30000.314453   -88.37360
1 -30000.314453   -88.37281
2 -30000.292969   -88.37300
3 -30000.238281   -88.37225
4 -28000.281250   -88.38554

In [5]:
df[['Field']]

            Field
0   -30000.314453
1   -30000.314453
2   -30000.292969
3   -30000.238281
4   -28000.281250
..            ...
243 -28000.158203
244 -30000.205078
245 -30000.205078
246 -30000.150391
247 -30000.216797

[248 rows x 1 columns]

In [6]:
df.iloc[0:2,:]

,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,Resistance.4,...,Field.7,Resistance.7,Field.8,Resistance.8,Field.9,Resistance.9,Field.10,Resistance.10,Field.11,Resistance.11
0,Oe,Ohm,Oe,Ohm,Oe,Ohm,Oe,Ohm,Oe,Ohm,...,Oe,Ohm,Oe,Ohm,Oe,Ohm,Oe,Ohm,Oe,Ohm
1,NaN,10K,NaN,50K,NaN,100K,NaN,150K,NaN,170K,...,NaN,230K,NaN,250K,NaN,260K,NaN,270K,NaN,280K

In [7]:
df = df.drop([0,1]).reset_index()

In [9]:
df.head()

,index,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,...,Field.7,Resistance.7,Field.8,Resistance.8,Field.9,Resistance.9,Field.10,Resistance.10,Field.11,Resistance.11
0,2,-10000.1337890625,3301.331,-10000.27734375,4215.815,-10000.0126953125,4177.697,-10000.2998046875,256.8307,170.171752929688,...,-10000.22265625,31116.59,-10000.1015625,31568.36,-9999.96875,19567.92,-10000.22265625,31637.71,-10000.0126953125,3731.195
1,3,-10000.189453125,3301.218,-10000.3212890625,4203.088,-9999.9912109375,4199.244,-10000.2998046875,271.1156,170.163925170898,...,-10000.2333984375,29977.07,-10000.0791015625,27473.27,-9999.96875,21880.38,-10000.189453125,27208.45,-9999.98046875,3959.863
2,4,-10000.1337890625,3301.377,-10000.3212890625,4197.347,-10000.0244140625,4235.337,-10000.310546875,257.6828,170.156616210938,...,-10000.244140625,20090.52,-10000.0791015625,29635.33,-9999.9912109375,15855.44,-10000.2109375,22530.59,-10000.001953125,3889.721
3,5,-10000.123046875,3301.445,-10000.2890625,4201.712,-10000.001953125,4214.067,-10000.34375,265.4473,170.154602050781,...,-10000.22265625,7122.811,-10000.1123046875,23933.73,-9999.9248046875,19335.75,-10000.244140625,23878.17,-10000.0126953125,3995.732
4,6,-9000.3486328125,3301.919,-9000.2607421875,4208.062,-9000.2607421875,4197.163,-9000.2607421875,316.0423,170.119277954102,...,-9000.2607421875,8929.288,-9000.171875,24103.23,-9000.2275390625,20228.14,-9000.271484375,26061.5,-9000.216796875,2933.907

In [10]:
df.drop('index', axis =1, inplace= True)

In [11]:
df

,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,Resistance.4,...,Field.7,Resistance.7,Field.8,Resistance.8,Field.9,Resistance.9,Field.10,Resistance.10,Field.11,Resistance.11
0,-10000.1337890625,3301.331,-10000.27734375,4215.815,-10000.0126953125,4177.697,-10000.2998046875,256.8307,170.171752929688,920.3052,...,-10000.22265625,31116.59,-10000.1015625,31568.36,-9999.96875,19567.92,-10000.22265625,31637.71,-10000.0126953125,3731.195
1,-10000.189453125,3301.218,-10000.3212890625,4203.088,-9999.9912109375,4199.244,-10000.2998046875,271.1156,170.163925170898,852.9095,...,-10000.2333984375,29977.07,-10000.0791015625,27473.27,-9999.96875,21880.38,-10000.189453125,27208.45,-9999.98046875,3959.863
2,-10000.1337890625,3301.377,-10000.3212890625,4197.347,-10000.0244140625,4235.337,-10000.310546875,257.6828,170.156616210938,1026.709,...,-10000.244140625,20090.52,-10000.0791015625,29635.33,-9999.9912109375,15855.44,-10000.2109375,22530.59,-10000.001953125,3889.721
3,-10000.123046875,3301.445,-10000.2890625,4201.712,-10000.001953125,4214.067,-10000.34375,265.4473,170.154602050781,983.4061,...,-10000.22265625,7122.811,-10000.1123046875,23933.73,-9999.9248046875,19335.75,-10000.244140625,23878.17,-10000.0126953125,3995.732
4,-9000.3486328125,3301.919,-9000.2607421875,4208.062,-9000.2607421875,4197.163,-9000.2607421875,316.0423,170.119277954102,2409.581,...,-9000.2607421875,8929.288,-9000.171875,24103.23,-9000.2275390625,20228.14,-9000.271484375,26061.5,-9000.216796875,2933.907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,-9000.1396484375,3302.95,-9000.2822265625,4240.766,-9000.2275390625,3245.083,-9000.3271484375,128.0525,170.001525878906,6892.802,...,NaN,NaN,-9000.171875,27732.31,-9000.0625,25868.72,-9000.0732421875,2984.129,NaN,NaN
164,-10000.33203125,3302.051,-9999.98046875,4242.414,-9999.9912109375,3216.603,-10000.1123046875,64.91466,170,8092.654,...,NaN,NaN,-10000.068359375,15295.08,-10000.244140625,30222.34,-10000.27734375,4201.452,NaN,NaN
165,-10000.3212890625,3302.05,-9999.9912109375,4246.745,-9999.98046875,3241.686,-10000.0791015625,93.5499,170.001235961914,7319.11,...,NaN,NaN,-10000.1123046875,14573.97,-10000.2109375,28681.51,-10000.265625,4009.316,NaN,NaN
166,-10000.2998046875,3302.277,-10000.0126953125,4247.96,-10000.0458984375,3236.555,-10000.03515625,115.3789,169.999282836914,7887.918,...,NaN,NaN,-10000.068359375,14256.14,-10000.2333984375,32360.43,-10000.27734375,3667.504,NaN,NaN
167,-10000.310546875,3302.183,-10000.001953125,4246.835,-9999.9912109375,3251.499,-10000.0791015625,NaN,169.999282836914,6994.964,...,NaN,NaN,-10000.068359375,16849.16,-10000.2109375,31616.58,-10000.27734375,4039.398,NaN,NaN

In [13]:
df.loc[0:3]

,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,Resistance.4,...,Field.7,Resistance.7,Field.8,Resistance.8,Field.9,Resistance.9,Field.10,Resistance.10,Field.11,Resistance.11
0,-10000.1337890625,3301.331,-10000.27734375,4215.815,-10000.0126953125,4177.697,-10000.2998046875,256.8307,170.171752929688,920.3052,...,-10000.22265625,31116.59,-10000.1015625,31568.36,-9999.96875,19567.92,-10000.22265625,31637.71,-10000.0126953125,3731.195
1,-10000.189453125,3301.218,-10000.3212890625,4203.088,-9999.9912109375,4199.244,-10000.2998046875,271.1156,170.163925170898,852.9095,...,-10000.2333984375,29977.07,-10000.0791015625,27473.27,-9999.96875,21880.38,-10000.189453125,27208.45,-9999.98046875,3959.863
2,-10000.1337890625,3301.377,-10000.3212890625,4197.347,-10000.0244140625,4235.337,-10000.310546875,257.6828,170.156616210938,1026.709,...,-10000.244140625,20090.52,-10000.0791015625,29635.33,-9999.9912109375,15855.44,-10000.2109375,22530.59,-10000.001953125,3889.721
3,-10000.123046875,3301.445,-10000.2890625,4201.712,-10000.001953125,4214.067,-10000.34375,265.4473,170.154602050781,983.4061,...,-10000.22265625,7122.811,-10000.1123046875,23933.73,-9999.9248046875,19335.75,-10000.244140625,23878.17,-10000.0126953125,3995.732

In [63]:
dftest = df.rolling(min_periods=5).mean()

TypeError: rolling() missing 1 required positional argument: 'window'

In [14]:
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=4)
dftest = df.rolling(window=indexer, min_periods=1).mean()

In [15]:
dftest.head(10)

,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,Resistance.4,...,Field.7,Resistance.7,Field.8,Resistance.8,Field.9,Resistance.9,Field.10,Resistance.10,Field.11,Resistance.11
0,-10000.145020,3301.34275,-10000.302246,4204.49050,-10000.007568,4206.58625,-10000.313477,262.769100,170.161724,945.832450,...,-10000.230713,22076.74775,-10000.093018,28152.6725,-9999.963379,19159.8725,-10000.216797,26313.7300,-10000.001953,3894.12775
1,-9750.198730,3301.48975,-9750.298096,4202.55225,-9750.069580,4211.45275,-9750.303711,277.572000,170.148605,1318.151400,...,-9750.240234,16529.92225,-9750.110596,26286.3900,-9750.028076,19324.9275,-9750.229004,24919.6775,-9750.052979,3694.80575
2,-9500.241211,3301.63825,-9500.269043,4203.35000,-9500.131348,4210.67575,-9500.296631,286.329275,170.134506,1812.585775,...,-9500.255127,11058.13275,-9500.136719,25588.4350,-9500.081787,18575.7150,-9500.263428,25260.9925,-9500.120361,3563.74325
3,-9250.308594,3301.77225,-9250.242920,4204.85475,-9250.187744,4200.72475,-9250.278564,297.142100,170.121643,2356.579525,...,-9250.264648,8227.64775,-9250.151855,24660.2075,-9250.146484,19373.1700,-9250.286865,26261.3475,-9250.182373,3395.46150
4,-9000.375977,3301.73350,-9000.230225,4204.76875,-9000.244141,4195.40500,-9000.255127,308.186400,170.108681,2823.404500,...,-9000.285156,8705.45725,-9000.158691,25392.9225,-9000.211182,19627.5200,-9000.302002,27651.4700,-9000.241699,3312.08900
5,-8750.377197,3301.69675,-8750.253418,4205.53200,-8750.267334,4188.92075,-8750.237183,295.364125,170.098560,2663.846750,...,-8750.283691,13352.40525,-8750.176758,25847.6075,-8750.231689,19504.2200,-8750.333618,26319.9725,-8750.264893,3365.46625
6,-8500.370239,3301.63500,-8500.293457,4207.27500,-8500.301758,4180.44375,-8500.219238,290.260200,170.089989,1994.696575,...,-8500.268555,18205.69975,-8500.202881,26104.2375,-8500.263184,19696.6450,-8500.356812,25302.2300,-8500.279785,3322.85675
7,-8250.360718,3301.64875,-8250.330566,4209.74725,-8250.336060,4174.17600,-8250.217773,286.871775,170.080769,1197.873163,...,-8250.259033,22549.74725,-8250.242676,26218.2000,-8250.278076,19553.1175,-8250.391113,23962.9725,-8250.294678,3332.41025
8,-8000.342773,3301.79400,-8000.351196,4212.39275,-8000.362061,4163.55900,-8000.194214,277.007575,170.071575,490.683902,...,-8000.254883,27140.70750,-8000.276978,25697.8100,-8000.317871,19117.1475,-8000.417236,21426.6450,-8000.309570,3192.88175
9,-7750.327759,3301.88075,-7750.305908,4213.26300,-7750.347046,4157.49125,-7750.225830,275.642525,170.063427,47.855227,...,-7750.253418,27407.71500,-7750.270020,25629.2250,-7750.299927,19166.4300,-7750.404785,22333.8750,-7750.269653,3216.11575

In [16]:
df.head(10)

,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,Resistance.4,...,Field.7,Resistance.7,Field.8,Resistance.8,Field.9,Resistance.9,Field.10,Resistance.10,Field.11,Resistance.11
0,-10000.1337890625,3301.331,-10000.27734375,4215.815,-10000.0126953125,4177.697,-10000.2998046875,256.8307,170.171752929688,920.3052,...,-10000.22265625,31116.59,-10000.1015625,31568.36,-9999.96875,19567.92,-10000.22265625,31637.71,-10000.0126953125,3731.195
1,-10000.189453125,3301.218,-10000.3212890625,4203.088,-9999.9912109375,4199.244,-10000.2998046875,271.1156,170.163925170898,852.9095,...,-10000.2333984375,29977.07,-10000.0791015625,27473.27,-9999.96875,21880.38,-10000.189453125,27208.45,-9999.98046875,3959.863
2,-10000.1337890625,3301.377,-10000.3212890625,4197.347,-10000.0244140625,4235.337,-10000.310546875,257.6828,170.156616210938,1026.709,...,-10000.244140625,20090.52,-10000.0791015625,29635.33,-9999.9912109375,15855.44,-10000.2109375,22530.59,-10000.001953125,3889.721
3,-10000.123046875,3301.445,-10000.2890625,4201.712,-10000.001953125,4214.067,-10000.34375,265.4473,170.154602050781,983.4061,...,-10000.22265625,7122.811,-10000.1123046875,23933.73,-9999.9248046875,19335.75,-10000.244140625,23878.17,-10000.0126953125,3995.732
4,-9000.3486328125,3301.919,-9000.2607421875,4208.062,-9000.2607421875,4197.163,-9000.2607421875,316.0423,170.119277954102,2409.581,...,-9000.2607421875,8929.288,-9000.171875,24103.23,-9000.2275390625,20228.14,-9000.271484375,26061.5,-9000.216796875,2933.907
5,-9000.359375,3301.812,-9000.205078125,4206.279,-9000.23828125,4196.136,-9000.271484375,306.1447,170.107528686523,2830.647,...,-9000.29296875,8089.912,-9000.18359375,24681.45,-9000.18359375,18883.53,-9000.3271484375,28573.71,-9000.25,3435.613
6,-9000.4033203125,3301.913,-9000.216796875,4203.366,-9000.25,4195.533,-9000.23828125,300.9341,170.105163574219,3202.684,...,-9000.2822265625,8768.58,-9000.1396484375,25922.42,-9000.25,19045.26,-9000.3046875,26532.01,-9000.25,3216.594
7,-9000.392578125,3301.29,-9000.23828125,4201.368,-9000.2275390625,4192.788,-9000.25,309.6245,170.102752685547,2850.706,...,-9000.3046875,9034.049,-9000.1396484375,26864.59,-9000.18359375,20353.15,-9000.3046875,29438.66,-9000.25,3662.242
8,-8000.353515625,3301.772,-8000.353515625,4211.115,-8000.353515625,4171.226,-8000.18896484375,264.7532,170.078796386719,1771.35,...,-8000.2548828125,27517.08,-8000.244140625,25921.97,-8000.3095703125,19734.94,-8000.39794921875,20735.51,-8000.3095703125,3147.416
9,-8000.33154296875,3301.565,-8000.365234375,4213.251,-8000.3759765625,4162.228,-8000.19970703125,285.729,170.0732421875,154.0463,...,-8000.232421875,27503.09,-8000.2880859375,25707.97,-8000.3095703125,19653.23,-8000.419921875,24502.74,-8000.3095703125,3265.175

In [17]:
df_avgd = dftest

df_avgd = df.groupby()

df.iloc[:5]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Field          168 non-null    object
 1   Resistance     168 non-null    object
 2   Field.1        168 non-null    object
 3   Resistance.1   168 non-null    object
 4   Field.2        168 non-null    object
 5   Resistance.2   168 non-null    object
 6   Field.3        168 non-null    object
 7   Resistance.3   164 non-null    object
 8   Field.4        168 non-null    object
 9   Resistance.4   167 non-null    object
 10  Field.5        168 non-null    object
 11  Resistance.5   168 non-null    object
 12  Field.6        168 non-null    object
 13  Resistance.6   161 non-null    object
 14  Field.7        40 non-null     object
 15  Resistance.7   40 non-null     object
 16  Field.8        168 non-null    object
 17  Resistance.8   168 non-null    object
 18  Field.9        168 non-null    object
 19  Resistance.9   168 non-null    object
 20  Field.10       168 non-null    object
 21  Resistance.10  168 non-null    object
 22  Field.11       48 non-null     object
 23  Resistance.11  48 non-null     object
dtypes: object(24)
memory usage: 31.6+ KB

In [22]:
df = df.astype(float)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Field          168 non-null    float64
 1   Resistance     168 non-null    float64
 2   Field.1        168 non-null    float64
 3   Resistance.1   168 non-null    float64
 4   Field.2        168 non-null    float64
 5   Resistance.2   168 non-null    float64
 6   Field.3        168 non-null    float64
 7   Resistance.3   164 non-null    float64
 8   Field.4        168 non-null    float64
 9   Resistance.4   167 non-null    float64
 10  Field.5        168 non-null    float64
 11  Resistance.5   168 non-null    float64
 12  Field.6        168 non-null    float64
 13  Resistance.6   161 non-null    float64
 14  Field.7        40 non-null     float64
 15  Resistance.7   40 non-null     float64
 16  Field.8        168 non-null    float64
 17  Resistance.8   168 non-null    float64
 18  Field.9        168 non-null    float64
 19  Resistance.9   168 non-null    float64
 20  Field.10       168 non-null    float64
 21  Resistance.10  168 non-null    float64
 22  Field.11       48 non-null     float64
 23  Resistance.11  48 non-null     float64
dtypes: float64(24)
memory usage: 31.6 KB

In [89]:
dftest = df.iloc[:3].mean(axis=0)

In [91]:
dftest

Field          -10000.176367
resistence        -11.420672
Field.1        -10000.363086
resistence.1      -11.331966
Field.2         -9999.887695
resistence.2      -11.214444
Field.3         -9999.991211
resistence.3      -11.064922
Field.4        -10000.325586
resistence.4      -10.896764
Field.5        -10000.208984
resistence.5      -10.747154
Field.6         -9999.951172
resistence.6      -10.075326
Field.7         -9999.874414
resistence.7       -9.698345
Field.8         -9999.867969
resistence.8       -9.669990
Field.9         -9999.773242
resistence.9       -9.735624
dtype: float64

In [127]:
for row in df.iterrows():
    df.loc[row:row+4].mean(axis=0).to_frame()
    row = row+5

TypeError: can only concatenate tuple (not "int") to tuple

In [137]:
df2= df.loc[0:3].mean(axis=0)

In [138]:
df2= df2.to_frame()

In [141]:
df2.T

,Field,resistence,Field.1,resistence.1,Field.2,resistence.2,Field.3,resistence.3,Field.4,resistence.4,Field.5,resistence.5,Field.6,resistence.6,Field.7,resistence.7,Field.8,resistence.8,Field.9,resistence.9
0,-10000.176367,-11.420672,-10000.363086,-11.331966,-9999.887695,-11.214444,-9999.991211,-11.064922,-10000.325586,-10.896764,-10000.208984,-10.747154,-9999.951172,-10.075326,-9999.874414,-9.698345,-9999.867969,-9.66999,-9999.773242,-9.735624

In [20]:
for row in df.iterrows():
    df2 = df.loc[:3].mean().to_frame().T

In [145]:
df.loc[0:3].mean(axis=0).to_frame().T

,Field,resistence,Field.1,resistence.1,Field.2,resistence.2,Field.3,resistence.3,Field.4,resistence.4,Field.5,resistence.5,Field.6,resistence.6,Field.7,resistence.7,Field.8,resistence.8,Field.9,resistence.9
0,-10000.176367,-11.420672,-10000.363086,-11.331966,-9999.887695,-11.214444,-9999.991211,-11.064922,-10000.325586,-10.896764,-10000.208984,-10.747154,-9999.951172,-10.075326,-9999.874414,-9.698345,-9999.867969,-9.66999,-9999.773242,-9.735624

In [24]:
df2 = df.groupby(np.arange(len(df)) // 4).mean()

In [25]:
df2

,Field,Resistance,Field.1,Resistance.1,Field.2,Resistance.2,Field.3,Resistance.3,Field.4,Resistance.4,...,Field.7,Resistance.7,Field.8,Resistance.8,Field.9,Resistance.9,Field.10,Resistance.10,Field.11,Resistance.11
0,-10000.145020,3301.34275,-10000.302246,4204.49050,-10000.007568,4206.58625,-10000.313477,262.769100,170.161724,945.832450,...,-10000.230713,22076.74775,-10000.093018,28152.67250,-9999.963379,19159.87250,-10000.216797,26313.73000,-10000.001953,3894.12775
1,-9000.375977,3301.73350,-9000.230225,4204.76875,-9000.244141,4195.40500,-9000.255127,308.186400,170.108681,2823.404500,...,-9000.285156,8705.45725,-9000.158691,25392.92250,-9000.211182,19627.52000,-9000.302002,27651.47000,-9000.241699,3312.08900
2,-8000.342773,3301.79400,-8000.351196,4212.39275,-8000.362061,4163.55900,-8000.194214,277.007575,170.071575,490.683902,...,-8000.254883,27140.70750,-8000.276978,25697.81000,-8000.317871,19117.14750,-8000.417236,21426.64500,-8000.309570,3192.88175
3,-7000.279541,3301.85100,-7000.144409,4217.26375,-7000.279419,4135.10900,-7000.301514,263.758850,170.042744,0.040191,...,-7000.207886,24143.98500,-7000.218872,24946.16250,-7000.240601,18831.69000,-7000.339722,24039.20250,-7000.174927,3239.59500
4,-6000.334351,3301.97550,-6000.210449,4217.05900,-6000.196533,4145.61775,-6000.337158,258.247075,170.029762,0.065764,...,-6000.232544,27459.89250,-6000.290161,30303.94750,-6000.284546,18834.84000,-6000.248901,23272.59250,-6000.356323,3272.69350
5,-5000.248657,3302.16400,-5000.138672,4226.04750,-5000.394531,4075.84500,-5000.287231,245.957425,170.021896,3675.386750,...,-5000.333862,27325.37750,-5000.190918,26916.05250,-5000.378052,19510.42750,-5000.188232,22887.32000,-5000.278931,3379.68775
6,-4000.229248,3302.27050,-4000.262268,4227.76125,-4000.201660,4058.75975,-4000.267822,78.485430,170.016693,3190.076250,...,-4000.303528,29938.22750,-4000.215454,25779.45750,-4000.207214,20813.48250,-4000.135681,21165.77750,-4000.273132,3075.93525
7,-3000.259216,3302.52875,-3000.132751,4228.93825,-3000.256531,3964.85475,-3000.143738,103.816147,170.013199,5473.124250,...,-3000.184937,29513.37500,-3000.380310,22753.68000,-3000.223511,21458.95750,-3000.132690,23784.25750,-3000.151978,24426.51425
8,-2000.358154,3302.91700,-2000.074646,4229.60075,-2000.008636,3886.63200,-2000.344360,76.972638,170.009361,7598.196500,...,-2000.261810,27317.27750,-2000.297607,26997.02000,-2000.297607,11463.84025,-2000.104980,22378.42000,-2000.371918,23161.07500
9,-1000.355148,3303.02600,-1000.225845,4235.38925,-1000.190063,3857.26500,-1000.242340,97.573057,170.006805,7197.982250,...,-1000.305618,28148.17000,-1000.181808,24391.19500,-1000.190109,19331.49250,-1000.267090,24390.31500,-1000.267105,16770.92125
10,-0.126572,3303.49025,-0.277908,4232.74775,-0.236634,3859.43725,-0.283411,77.892660,170.004940,7206.241750,...,NaN,NaN,-0.357703,24723.64750,-0.385219,19439.65250,-0.297169,24860.15000,-0.277908,2253.53275
11,1000.146027,3304.06100,1000.008484,4230.92125,1000.038712,3884.78725,999.978165,101.339537,170.002510,9034.081750,...,NaN,NaN,1000.041489,24283.77250,1000.013977,29592.59250,999.947937,21319.82500,999.961700,1842.60500
12,1999.780334,3304.54600,1999.777588,4235.05850,1999.843597,3843.64200,1999.890381,98.659167,170.002125,6970.213250,...,NaN,NaN,1999.810547,24683.02000,1999.810547,27372.66250,1999.876648,22032.73000,NaN,NaN
13,3000.017090,3304.44700,3000.168457,4237.60350,2999.629272,3835.73525,3000.121643,62.835565,170.000004,6908.313500,...,NaN,NaN,3000.179504,24889.81250,3000.176819,27953.41250,3000.096863,5534.50825,NaN,NaN
14,4000.028381,3304.52725,3999.901855,4242.30275,3999.959595,3839.59675,3999.888000,226.778450,169.998955,7463.464750,...,NaN,NaN,4000.207153,24226.20500,4000.207214,25671.91500,4000.011902,2927.15700,NaN,NaN
15,4999.976196,3305.00650,4999.849731,4243.73800,4999.885376,3809.05725,4999.813965,1291.711500,169.999149,7524.958750,...,NaN,NaN,5000.025879,25314.46000,4999.989990,27594.86750,4999.816772,2986.67850,NaN,NaN
16,6000.265259,3305.50650,6000.100342,4243.49300,6000.119751,3802.55600,6000.031616,1485.646800,169.999626,8374.966250,...,NaN,NaN,6000.114258,25449.56250,6000.422241,28677.98000,6000.207886,3060.83100,NaN,NaN
17,7000.183228,3306.20225,7000.196899,4243.82425,7000.092163,3769.46575,7000.152832,859.915725,170.000118,8522.108500,...,NaN,NaN,7000.053833,25332.63500,7000.175049,23290.14750,7000.177612,3058.98900,NaN,NaN
18,8000.086670,3306.70050,8000.249390,4244.68250,8000.285156,3717.60950,8000.175171,801.758575,169.999798,6775.367333,...,NaN,NaN,8000.252197,24522.99750,8000.083984,30243.57250,8000.345581,3420.80250,NaN,NaN
19,9000.114746,3307.25925,9000.221924,4243.79450,9000.252197,3675.15775,9000.150391,256.391150,169.999546,5187.892750,...,NaN,NaN,9000.218994,25634.82250,9000.065186,29390.65750,9000.169434,3273.75650,NaN,NaN
20,10000.359863,3307.66800,10000.337891,4244.33250,10000.117676,3667.39150,10000.280029,69.742310,170.001186,6025.805500,...,NaN,NaN,10000.076416,25224.43750,10000.335205,26959.40500,10000.302246,3466.37175,NaN,NaN
21,10000.345947,3307.70200,10000.312988,4244.17675,10000.125977,3611.01400,10000.263184,136.937675,170.000271,12209.272500,...,NaN,NaN,10000.076660,24179.22500,10000.305176,29599.95250,10000.280029,3785.98300,NaN,NaN
22,9000.362793,3307.19625,9000.348877,4246.44575,9000.224854,3588.82975,9000.310059,107.079527,169.999756,11627.667500,...,NaN,NaN,9000.354248,24460.72750,9000.354248,27076.18250,9000.318604,3078.97425,NaN,NaN
23,8000.255127,3307.05350,8000.227051,4240.68350,8000.235474,3616.71925,8000.285156,94.586565,170.000175,6081.783500,...,NaN,NaN,8000.246704,24796.22000,8000.364868,28002.01750,8000.194214,3339.57650,NaN,NaN
24,7000.196899,3306.55375,7000.339844,4239.17450,7000.196899,3586.67400,7000.271118,882.120750,170.000637,6278.902250,...,NaN,NaN,7000.207886,25764.74750,7000.317993,30102.69500,7000.174927,3196.43125,NaN,NaN
25,6000.257080,3306.34050,6000.243408,4242.49725,6000.251709,3604.40125,6000.317627,826.048575,170.000046,8054.435250,...,NaN,NaN,6000.246216,25771.54250,6000.235229,26746.42250,6000.348145,3045.76350,NaN,NaN
26,5000.160767,3306.14225,5000.144287,4241.70875,5000.301025,3493.54800,5000.356079,737.661150,170.000317,8181.267750,...,NaN,NaN,5000.155273,27142.93250,5000.163452,28894.29000,5000.256714,3242.82800,NaN,NaN
27,4000.234741,3305.85275,4000.342041,4242.36500,4000.336609,3420.40875,4000.121948,698.798450,170.001129,7569.518500,...,NaN,NaN,4000.204468,26528.46750,4000.336609,29311.35750,4000.196228,3294.38000,NaN,NaN
28,3000.361023,3305.98700,3000.289490,4246.51075,3000.308716,3433.23775,3000.228943,327.085875,170.000694,8011.889750,...,NaN,NaN,3000.339111,25295.73500,3000.311523,28088.73250,3000.314270,3029.10000,NaN,NaN
29,2000.146301,3305.53500,2000.204041,4249.10700,2000.074646,3381.07500,2000.135284,222.057175,170.000778,8508.806500,...,NaN,NaN,2000.215057,24798.88000,2000.077393,28277.35750,2000.060883,2995.39325,NaN,NaN
30,1000.352432,3305.40900,1000.132294,4248.68900,1000.280853,3395.62025,1000.341400,712.690825,170.000355,8562.964000,...,NaN,NaN,1000.151550,26372.17750,1000.313858,29538.23500,1000.291840,3469.47250,NaN,NaN
31,0.101808,3305.39075,0.294417,4259.24250,0.002752,3299.47125,0.068789,77.231390,170.001160,8408.671000,...,NaN,NaN,0.338442,25749.44250,0.060534,29503.35250,0.321933,3158.32075,NaN,NaN
32,-1000.143295,3305.45275,-1000.091003,4255.01300,-999.637024,3338.09500,-1000.327652,67.841718,170.000401,8832.987500,...,NaN,NaN,-1000.063507,24629.14500,-1000.206589,29433.84000,-999.939682,2956.72425,NaN,NaN
33,-1999.653717,3305.06175,-1999.893097,4254.74325,-1999.785797,3306.44075,-1999.703308,725.347000,170.001385,8798.059250,...,NaN,NaN,-1999.868378,23567.41000,-1999.733490,29929.82000,-1999.816040,2901.23825,NaN,NaN
34,-3000.022583,3304.83750,-3000.248230,4254.74700,-3000.118896,3287.59250,-3000.041931,793.146800,170.000847,8343.483250,...,NaN,NaN,-3000.237305,24778.85500,-3000.099670,30179.86000,-3000.179443,3087.94100,NaN,NaN
35,-4000.132813,3304.57725,-3999.810913,4250.08425,-4000.218201,3294.28050,-3999.899048,72.694203,170.000217,7453.580000,...,NaN,NaN,-4000.042114,23190.91750,-4000.190613,28719.46250,-3999.706482,3081.23600,NaN,NaN
36,-4999.720459,3304.05000,-4999.813843,4253.80750,-4999.678955,3283.05225,-5000.047852,90.931988,170.000622,7069.407000,...,NaN,NaN,-5000.212891,24306.95500,-4999.769897,28777.46750,-4999.868896,2956.78450,NaN,NaN
37,-5999.935181,3303.85525,-6000.179810,4250.90825,-6000.045044,3303.69325,-5999.979614,89.305367,170.000877,7371.339000,...,NaN,NaN,-6000.149658,22953.25750,-5999.981934,27436.60750,-6000.086548,3087.26300,NaN,NaN
38,-7000.326172,3303.79375,-7000.130493,4251.86225,-7000.001465,3281.83550,-7000.064819,76.206070,170.001022,8002.284500,...,NaN,NaN,-7000.092163,27285.24000,-6999.935547,28057.76500,-7000.004150,2981.14425,NaN,NaN
39,-8000.224243,3302.79075,-8000.186035,4250.15450,-8000.053955,3309.74950,-8000.114380,95.789575,170.000317,7719.309000,...,NaN,NaN,-7999.998779,2218.41625,-8000.274048,28199.62000,-8000.339966,3038.46175,NaN,NaN
40,-9000.111816,3302.88050,-9000.241211,4242.89100,-9000.249512,3268.95525,-9000.296387,102.344415,170.000961,7112.716750,...,NaN,NaN,-9000.171875,22598.58250,-9000.048584,28794.25750,-9000.098145,3178.13300,NaN,NaN
41,-10000.315918,3302.14025,-9999.996582,4245.98850,-10000.002197,3236.58575,-10000.076416,91.281153,169.999950,7573.661500,...,NaN,NaN,-10000.079346,15243.58750,-10000.224854,30720.21500,-10000.274414,3979.41750,NaN,NaN

In [26]:
df2.to_csv('S117New_Processed.csv')